### PR TITLE
Move to gtest

### PR DESCRIPTION
**Pull request by cjappl**
doctest has cmake deprecation issues, move to the more supported library

### CODE REVIEW

**Comment by atsushieno** [comment]
just a heads up, I think you need updates in GitHub Actions test setup too.

**Comment by cjappl** [comment]
> just a heads up, I think you need updates in GitHub Actions test setup too.

I think everything worked here, the builds for this PR passed. Can you elaborate on the problem you're seeing?

**Comment by atsushieno** [comment]
Oops, sorry, never mind. Those tests were somehow taking quite long time locally so that I perceived the wrong impression that the tests never run just by `ctest` command tool (they actually do).

**Comment by cjappl** [comment]
> Oops, sorry, never mind. Those tests were somehow taking quite long time locally so that I perceived the wrong impression that the tests never run just by `ctest` command tool (they actually do).

Thanks for checking for me! Always a possibility I messed something up 😁

**Pull request merged**
