### PR TITLE
Add Logv(), a va_list variant of Log() function.

### PR DESCRIPTION
**Pull request by atsushieno**
This fixes https://github.com/cjappl/rtlog-cpp/issues/11 .

### CODE REVIEW

**Review by cjappl — DISMISSED** [review]

**Comment by cjappl** [comment]
Thanks for the contribution, great catch. I'll submit as long as tests pass

**Comment by cjappl** [comment]
(will you fix the tests, and possibly add a new one, and then I'll submit this?) 

Thanks again for the contribution

**Comment by atsushieno** [comment]
Oops, my bad...! I just added a fix commit.

**Comment by atsushieno** [comment]
Let me check the existing tests so that I can add some.

**Comment by cjappl** [comment]
I'm going to merge this, and you can follow on with a test PR if you want. I would recommend it, if you have time, but I understand you might be busy!

Thanks again for seeing a problem, reporting it, then fixing the issue, very much appreciated. Any additional contributions welcome.

**Comment by atsushieno** [comment]
I was a bit late ;-)  I just created another PR for it anyway. Please have a look. Thanks!

**Pull request merged**
